version: '3'
services:
  web:
    image: ${DOCKER_IMAGE}
    build:
      context: .
    environment:
      API_URL: ${API_URL}
      BASE_URL: ${BASE_URL}
      WEBSOCKET: ${WEBSOCKET}
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "50m"
    ports:
      - "${HOST_PORT}:80"
